language: php

sudo: false

php:
  - 7.4
  - 8.0

env:
  - dependencies=highest
  - dependencies=lowest

matrix:
  fast_finish: true

install:
  - composer install -n

before_script:
  - case "${dependencies}" in
      "lowest")
        composer update --prefer-lowest --prefer-stable -n
        ;;
      *)
        composer update --prefer-stable -n
        ;;
    esac

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: always

cache:
  directories:
    - vendor/
    - $HOME/.composer/cache/files
